import fs from "fs";
import path from "path";
import { districtMarketMap } from "../scraper/districtMarketMap";

// All 38 Tamil Nadu Districts metadata
export const TN_DISTRICTS_DATA = [
  { code: "TN-ARI", nameEn: "Ariyalur", nameTa: "அரியலூர்", collector: "Collectorate, Jayankondam Road, Ariyalur - 621704", agri: "JDA Office, Mini Civil Station, Ariyalur", crops: ["Paddy", "Cashew", "Sugarcane", "Groundnut"], rainfall: 954, soil: ["Red Loam", "Clay Soil", "Black Soil"], climate: "North Eastern Agro-Climatic Zone" },
  { code: "TN-CGL", nameEn: "Chengalpattu", nameTa: "செங்கல்பட்டு", collector: "Collectorate, GST Road, Chengalpattu - 603001", agri: "JDA Office, GST Road, Chengalpattu", crops: ["Paddy", "Groundnut", "Watermelon", "Vegetables"], rainfall: 1200, soil: ["Alluvial", "Sandy Clay", "Red Soil"], climate: "North Eastern Agro-Climatic Zone" },
  { code: "TN-CHE", nameEn: "Chennai", nameTa: "சென்னை", collector: "Collectorate, Rajaji Salai, Chennai - 600001", agri: "Directorate of Agri Marketing, Guindy, Chennai", crops: ["Urban Horticulture", "Micro-Greens"], rainfall: 1400, soil: ["Coastal Alluvium"], climate: "Coastal Agro-Climatic Zone" },
  { code: "TN-CBE", nameEn: "Coimbatore", nameTa: "கோயம்புத்தூர்", collector: "Collectorate, State Bank Road, Coimbatore - 641018", agri: "JDA Office, TNAU Campus, Coimbatore", crops: ["Coconut", "Cotton", "Banana", "Vegetables", "Turmeric"], rainfall: 650, soil: ["Red Loam", "Black Cotton Soil"], climate: "Western Agro-Climatic Zone" },
  { code: "TN-[#38]", nameEn: "Cuddalore", nameTa: "கடலூர்", collector: "Collectorate, Beach Road, Cuddalore - 607001", agri: "JDA Office, Semmandalam, Cuddalore", crops: ["Paddy", "Cashew", "Sugarcane", "Jackfruit"], rainfall: 1210, soil: ["Coastal Alluvium", "Red Sandy Loam"], climate: "North Eastern Agro-Climatic Zone" },
  { code: "TN-DPI", nameEn: "Dharmapuri", nameTa: "தர்மபுரி", collector: "Collectorate, Nethaji Bypass Road, Dharmapuri - 636705", agri: "JDA Office, Collectorate Complex, Dharmapuri", crops: ["Mango", "Tomato", "Ragi", "Pulses", "Flowers"], rainfall: 895, soil: ["Red Soil", "Black Soil"], climate: "North Western Agro-Climatic Zone" },
  { code: "TN-DGL", nameEn: "Dindigul", nameTa: "திண்டுக்கல்", collector: "Collectorate, Velunatchiyar Campus, Dindigul - 624004", agri: "JDA Office, Collectorate Annexe, Dindigul", crops: ["Onion", "Garlic", "Banana", "Maize", "Flowers"], rainfall: 830, soil: ["Red Loam", "Black Soil"], climate: "Southern Agro-Climatic Zone" },
  { code: "TN-ERD", nameEn: "Erode", nameTa: "ஈரோடு", collector: "Collectorate, Brough Road, Erode - 638011", agri: "JDA Office, Sampath Nagar, Erode", crops: ["Turmeric", "Sugarcane", "Paddy", "Banana", "Coconut"], rainfall: 710, soil: ["Red Soil", "Black Cotton Soil"], climate: "Western Agro-Climatic Zone" },
  { code: "TN-KLK", nameEn: "Kallakurichi", nameTa: "கள்ளக்குறிச்சி", collector: "Collectorate, Kachirayapalayam Road, Kallakurichi - 606202", agri: "JDA Office, District Collectorate, Kallakurichi", crops: ["Sugarcane", "Paddy", "Maize", "Groundnut", "Tapioca"], rainfall: 1070, soil: ["Red Loam", "Clay Soil"], climate: "North Eastern Agro-Climatic Zone" },
  { code: "TN-KCP", nameEn: "Kancheepuram", nameTa: "காஞ்சிபுரம்", collector: "Collectorate, Vandavasi Road, Kancheepuram - 631501", agri: "JDA Office, Collectorate Campus, Kancheepuram", crops: ["Paddy", "Sugarcane", "Groundnut", "Brinjal"], rainfall: 1205, soil: ["Clay Loam", "Alluvial"], climate: "North Eastern Agro-Climatic Zone" },
  { code: "TN-KKI", nameEn: "Kanniyakumari", nameTa: "கன்யாகுமரி", collector: "Collectorate, Nagercoil - 629001", agri: "JDA Office, Collectorate Complex, Nagercoil", crops: ["Rubber", "Banana", "Coconut", "Paddy", "Tapioca"], rainfall: 1465, soil: ["Laterite", "Red Loam", "Coastal Sand"], climate: "High Rainfall Agro-Climatic Zone" },
  { code: "TN-KRR", nameEn: "Karur", nameTa: "கரூர்", collector: "Collectorate, Thanthonimalai, Karur - 639007", agri: "JDA Office, Thanthonimalai, Karur", crops: ["Banana", "Moringa", "Paddy", "Sugarcane", "Groundnut"], rainfall: 655, soil: ["Red Soil", "Alluvial Soil"], climate: "Southern Agro-Climatic Zone" },
  { code: "TN-KGI", nameEn: "Krishnagiri", nameTa: "கிருஷ்ணகிரி", collector: "Collectorate, Rayakottah Road, Krishnagiri - 635115", agri: "JDA Office, Collectorate Complex, Krishnagiri", crops: ["Mango", "Tomato", "Flowers", "Ragi", "Coconut"], rainfall: 840, soil: ["Red Loam", "Black Soil"], climate: "North Western Agro-Climatic Zone" },
  { code: "TN-MDU", nameEn: "Madurai", nameTa: "மதுரை", collector: "Collectorate, KK Nagar Road, Madurai - 625020", agri: "JDA Office, Tallakulam, Madurai", crops: ["Jasmine", "Paddy", "Cotton", "Sugarcane", "Pulses"], rainfall: 850, soil: ["Red Soil", "Black Soil"], climate: "Southern Agro-Climatic Zone" },
  { code: "TN-MAY", nameEn: "Mayiladuthurai", nameTa: "மயிலாடுதுறை", collector: "Collectorate, Collectorate Campus, Mayiladuthurai - 609001", agri: "JDA Office, Court Complex Road, Mayiladuthurai", crops: ["Paddy", "Pulses", "Coconut", "Groundnut"], rainfall: 1350, soil: ["Deltaic Alluvium", "Coastal Clay"], climate: "Cauvery Delta Agro-Climatic Zone" },
  { code: "TN-NGP", nameEn: "Nagapattinam", nameTa: "நாகப்பட்டினம்", collector: "Collectorate, Public Office Road, Nagapattinam - 611001", agri: "JDA Office, Collectorate Campus, Nagapattinam", crops: ["Paddy", "Pulses", "Groundnut", "Cotton"], rainfall: 1340, soil: ["Coastal Alluvium", "Clay Soil"], climate: "Cauvery Delta Agro-Climatic Zone" },
  { code: "TN-NMK", nameEn: "Namakkal", nameTa: "நாமக்கல்", collector: "Collectorate, Mohanur Road, Namakkal - 637003", agri: "JDA Office, Collectorate Campus, Namakkal", crops: ["Poultry Feed (Maize)", "Tapioca", "Turmeric", "Groundnut"], rainfall: 780, soil: ["Red Soil", "Gravelly Soil"], climate: "North Western Agro-Climatic Zone" },
  { code: "TN-NLG", nameEn: "The Nilgiris", nameTa: "நீலகிரி", collector: "Collectorate, Finger Post, Udhagamandalam - 643001", agri: "JDA Office, Vijayanagaram, Ooty", crops: ["Potato", "Tea", "Carrot", "Cabbage", "Exotic Vegetables"], rainfall: 1920, soil: ["Laterite", "Peaty Soil"], climate: "Hilly Agro-Climatic Zone" },
  { code: "TN-PER", nameEn: "Perambalur", nameTa: "பெரம்பலூர்", collector: "Collectorate, Trichy Main Road, Perambalur - 621212", agri: "JDA Office, Collectorate Annexe, Perambalur", crops: ["Small Onion (Shallot)", "Cotton", "Maize", "Sugarcane"], rainfall: 860, soil: ["Black Soil", "Red Soil"], climate: "Central Agro-Climatic Zone" },
  { code: "TN-PDK", nameEn: "Pudukkottai", nameTa: "புதுக்கோட்டை", collector: "Collectorate, Collectorate Campus, Pudukkottai - 622005", agri: "JDA Office, Kalyanaramapuram, Pudukkottai", crops: ["Paddy", "Groundnut", "Cashew", "Coconut", "Sugarcane"], rainfall: 920, soil: ["Red Sandy Soil", "Coastal Alluvium"], climate: "Southern Agro-Climatic Zone" },
  { code: "TN-RMD", nameEn: "Ramanathapuram", nameTa: "இராமநாதபுரம்", collector: "Collectorate, Collectorate Complex, Ramanathapuram - 623503", agri: "JDA Office, Collectorate Campus, Ramanathapuram", crops: ["Chilli (Mundu Chilli)", "Paddy", "Cotton", "Coconut"], rainfall: 825, soil: ["Saline Coastal Soil", "Sandy Soil"], climate: "Southern Agro-Climatic Zone" },
  { code: "TN-RPT", nameEn: "Ranipet", nameTa: "ராணிப்பேட்டை", collector: "Collectorate, Ranipet - 632401", agri: "JDA Office, Master Plan Complex, Ranipet", crops: ["Paddy", "Sugarcane", "Groundnut", "Banana"], rainfall: 1040, soil: ["Clay Loam", "Red Soil"], climate: "North Eastern Agro-Climatic Zone" },
  { code: "TN-SLM", nameEn: "Salem", nameTa: "சேலம்", collector: "Collectorate, Collectorate Campus, Salem - 636001", agri: "JDA Office, Hasthampatti, Salem", crops: ["Mango", "Tapioca", "Tomato", "Turmeric", "Coffee"], rainfall: 990, soil: ["Red Loam", "Black Soil"], climate: "North Western Agro-Climatic Zone" },
  { code: "TN-SVG", nameEn: "Sivagangai", nameTa: "சிவகங்கை", collector: "Collectorate, Maruthupandiyar Nagar, Sivagangai - 630562", agri: "JDA Office, Collectorate Complex, Sivagangai", crops: ["Paddy", "Groundnut", "Sugarcane", "Pulses"], rainfall: 900, soil: ["Red Soil", "Laterite Soil"], climate: "Southern Agro-Climatic Zone" },
  { code: "TN-TKS", nameEn: "Tenkasi", nameTa: "தென்காசி", collector: "Collectorate, Tenkasi - 627811", agri: "JDA Office, District Collectorate, Tenkasi", crops: ["Paddy", "Banana", "Lemon", "Spices", "Sugarcane"], rainfall: 1100, soil: ["Red Loam", "Alluvial Soil"], climate: "Southern Agro-Climatic Zone" },
  { code: "TN-TNJ", nameEn: "Thanjavur", nameTa: "தஞ்சாவூர்", collector: "Collectorate, Court Road, Thanjavur - 613001", agri: "JDA Office, Collectorate Campus, Thanjavur", crops: ["Paddy (Rice Bowl of TN)", "Coconut", "Pulses", "Sugarcane", "Banana"], rainfall: 1125, soil: ["Deltaic Alluvium", "Red Soil"], climate: "Cauvery Delta Agro-Climatic Zone" },
  { code: "TN-THN", nameEn: "Theni", nameTa: "தேனி", collector: "Collectorate, Collectorate Campus, Theni - 625531", agri: "JDA Office, Collectorate Annexe, Theni", crops: ["Banana", "Grape", "Cardamom", "Cotton", "Paddy"], rainfall: 845, soil: ["Red Loam", "Black Soil"], climate: "Southern Agro-Climatic Zone" },
  { code: "TN-TVR", nameEn: "Thiruvarur", nameTa: "திருவாரூர்", collector: "Collectorate, Master Plan Complex, Thiruvarur - 610004", agri: "JDA Office, Collectorate Campus, Thiruvarur", crops: ["Paddy", "Pulses", "Cotton", "Coconut"], rainfall: 1260, soil: ["Deltaic Alluvium"], climate: "Cauvery Delta Agro-Climatic Zone" },
  { code: "TN-TNM", nameEn: "Thiruvannamalai", nameTa: "திருவண்ணாமலை", collector: "Collectorate, Vengikkal, Thiruvannamalai - 606604", agri: "JDA Office, Vengikkal, Thiruvannamalai", crops: ["Groundnut", "Paddy", "Sugarcane", "Banana", "Flower"], rainfall: 1060, soil: ["Red Soil", "Sandy Loam"], climate: "North Eastern Agro-Climatic Zone" },
  { code: "TN-TKD", nameEn: "Thoothukudi", nameTa: "தூத்துக்குடி", collector: "Collectorate, Korampallam, Thoothukudi - 628101", agri: "JDA Office, Korampallam, Thoothukudi", crops: ["Chilli", "Cotton", "Onion", "Banana", "Pulses"], rainfall: 660, soil: ["Black Soil", "Coastal Sand"], climate: "Southern Agro-Climatic Zone" },
  { code: "TN-TPR", nameEn: "Tiruchirapalli", nameTa: "திருச்சிராப்பள்ளி", collector: "Collectorate, Cantonment, Tiruchirapalli - 620001", agri: "JDA Office, Collectorate Campus, Trichy", crops: ["Banana", "Paddy", "Onion", "Cotton", "Sugarcane"], rainfall: 818, soil: ["Alluvial", "Red Soil"], climate: "Cauvery Delta Agro-Climatic Zone" },
  { code: "TN-TNL", nameEn: "Tirunelveli", nameTa: "திருநெல்வேலி", collector: "Collectorate, Kokkirakulam, Tirunelveli - 627009", agri: "JDA Office, Kokkirakulam, Tirunelveli", crops: ["Paddy", "Banana", "Cotton", "Chilli", "Coconut"], rainfall: 880, soil: ["Alluvial", "Black Soil"], climate: "Southern Agro-Climatic Zone" },
  { code: "TN-TPT", nameEn: "Tirupattur", nameTa: "திருப்பத்தூர்", collector: "Collectorate, Tirupattur - 635601", agri: "JDA Office, Collectorate Campus, Tirupattur", crops: ["Paddy", "Sugarcane", "Mango", "Groundnut"], rainfall: 960, soil: ["Red Soil", "Clay Loam"], climate: "North Eastern Agro-Climatic Zone" },
  { code: "TN-[#39]", nameEn: "Tiruppur", nameTa: "திருப்பூர்", collector: "Collectorate, Palladam Road, Tiruppur - 641604", agri: "JDA Office, Collectorate Campus, Tiruppur", crops: ["Cotton", "Maize", "Coconut", "Groundnut", "Banana"], rainfall: 615, soil: ["Red Soil", "Black Soil"], climate: "Western Agro-Climatic Zone" },
  { code: "TN-TVL", nameEn: "Tiruvallur", nameTa: "திருவள்ளூர்", collector: "Collectorate, Tiruvallur - 602001", agri: "JDA Office, Collectorate Campus, Tiruvallur", crops: ["Paddy", "Sugarcane", "Mango", "Vegetables"], rainfall: 1104, soil: ["Clay Loam", "Sandy Soil"], climate: "North Eastern Agro-Climatic Zone" },
  { code: "TN-VLR", nameEn: "Vellore", nameTa: "வேலூர்", collector: "Collectorate, Sathuvachari, Vellore - 632009", agri: "JDA Office, Sathuvachari, Vellore", crops: ["Groundnut", "Sugarcane", "Paddy", "Banana"], rainfall: 990, soil: ["Red Loam", "Clay Soil"], climate: "North Eastern Agro-Climatic Zone" },
  { code: "TN-VPM", nameEn: "Villupuram", nameTa: "விழுப்புரம்", collector: "Collectorate, Master Plan Complex, Villupuram - 605602", agri: "JDA Office, Collectorate Campus, Villupuram", crops: ["Paddy", "Sugarcane", "Groundnut", "Cotton", "Tapioca"], rainfall: 1045, soil: ["Red Soil", "Clay Loam"], climate: "North Eastern Agro-Climatic Zone" },
  { code: "TN-VNR", nameEn: "Virudhunagar", nameTa: "விருதுநகர்", collector: "Collectorate, Collectorate Complex, Virudhunagar - 626002", agri: "JDA Office, Collectorate Campus, Virudhunagar", crops: ["Cotton", "Chilli", "Maize", "Pulses", "Oilseeds"], rainfall: 810, soil: ["Black Cotton Soil", "Red Soil"], climate: "Southern Agro-Climatic Zone" }
];

// Commodities dataset
export const TN_COMMODITIES_DATA = [
  { id: "TN-COM-TOM", en: "Tomato", ta: "தக்காளி", sci: "Solanum lycopersicum", cat: "Vegetables", sub: "Solanaceous", unit: "₹/Quintal", season: "Year-Round" },
  { id: "TN-COM-ONI", en: "Onion", ta: "வெங்காயம்", sci: "Allium cepa", cat: "Vegetables", sub: "Bulb", unit: "₹/Quintal", season: "Rabi" },
  { id: "TN-COM-POT", en: "Potato", ta: "உருளைக்கிழங்கு", sci: "Solanum tuberosum", cat: "Vegetables", sub: "Tuber", unit: "₹/Quintal", season: "Rabi" },
  { id: "TN-COM-BRI", en: "Brinjal", ta: "கத்தரிக்காய்", sci: "Solanum melongena", cat: "Vegetables", sub: "Solanaceous", unit: "₹/Quintal", season: "Year-Round" },
  { id: "TN-COM-CHL", en: "Chilli", ta: "மிளகாய்", sci: "Capsicum annuum", cat: "Spices & Condiments", sub: "Spice", unit: "₹/Quintal", season: "Kharif" },
  { id: "TN-COM-BHE", en: "Bhendi (Okra)", ta: "வெண்டைக்காய்", sci: "Abelmoschus esculentus", cat: "Vegetables", sub: "Fruit Vegetable", unit: "₹/Quintal", season: "Year-Round" },
  { id: "TN-COM-[#01]", en: "Drumstick (Moringa)", ta: "முருங்கைக்காய்", sci: "Moringa oleifera", cat: "Vegetables", sub: "Perennial", unit: "₹/Quintal", season: "Year-Round" },
  { id: "TN-COM-BAN", en: "Banana", ta: "வாழைப்பழம்", sci: "Musa acuminata", cat: "Fruits", sub: "Tropical Fruit", unit: "₹/Quintal", season: "Year-Round" },
  { id: "TN-COM-COC", en: "Coconut", ta: "தேங்காய்", sci: "Cocos nucifera", cat: "Oilseeds", sub: "Palm", unit: "₹/Thousand Nuts", season: "Year-Round" },
  { id: "TN-COM-GND", en: "Groundnut", ta: "நிலக்கடலை", sci: "Arachis hypogaea", cat: "Oilseeds", sub: "Legume Oilseed", unit: "₹/Quintal", season: "Kharif" },
  { id: "TN-COM-TUR", en: "Turmeric", ta: "மஞ்சள்", sci: "Curcuma longa", cat: "Spices & Condiments", sub: "Rhizome Spice", unit: "₹/Quintal", season: "Rabi" },
  { id: "TN-COM-SUG", en: "Sugarcane", ta: "கரும்பு", sci: "Saccharum officinarum", cat: "Commercial Crops", sub: "Sugar Crop", unit: "₹/Ton", season: "Year-Round" },
  { id: "TN-COM-PAD", en: "Paddy (Rice)", ta: "நெல்", sci: "Oryza sativa", cat: "Cereals & Pulses", sub: "Cereal Grain", unit: "₹/Quintal", season: "Kharif" },
  { id: "TN-COM-COT", en: "Cotton", ta: "பருத்தி", sci: "Gossypium hirsutum", cat: "Commercial Crops", sub: "Fiber Crop", unit: "₹/Quintal", season: "Kharif" },
  { id: "TN-COM-MAN", en: "Mango", ta: "மாம்பழம்", sci: "Mangifera indica", cat: "Fruits", sub: "Tree Fruit", unit: "₹/Quintal", season: "Zaid" },
  { id: "TN-COM-JAS", en: "Jasmine (Mullai)", ta: "மல்லிகை", sci: "Jasminum sambac", cat: "Flowers", sub: "Commercial Flower", unit: "₹/Kg", season: "Year-Round" }
];

console.log("Master dataset generator ready.");
