// districtMarketMap.ts
// Static compiled mapping of Uzhavar Sandhai Market Name -> District Name in Tamil Nadu

export const districtMarketMap: Record<string, string> = {
  "Kancheepuram": "Kancheepuram",
  "Padappai": "Kancheepuram",
  "Sunguvarchatram": "Kancheepuram",
  "Kundrathur": "Kancheepuram",
  "Tiruthani": "Tiruvallur",
  "Tiruvallur": "Tiruvallur",
  "Ambattur": "Tiruvallur",
  "Paruthipattu": "Tiruvallur",
  "Naravarikuppam": "Tiruvallur",
  "Perambakkam": "Tiruvallur",
  "Cuddalore": "Cuddalore",
  "Chidambaram": "Cuddalore",
  "Viruthachalam": "Cuddalore",
  "Panruti": "Cuddalore",
  "Vadalur": "Cuddalore",
  "Kattumannarkoil": "Cuddalore",
  "Tindivanam": "Villupuram",
  "Villupuram": "Villupuram",
  "Gingee": "Villupuram",
  "Vikravandi": "Villupuram",
  "Vellore": "Vellore",
  "Katpadi": "Vellore",
  "Gudiyatham": "Vellore",
  "Kahithapattarai": "Vellore",
  "Pallikonda": "Vellore",
  "Pernampet": "Vellore",
  "Tiruvannamalai": "Thiruvannamalai",
  "Polur": "Thiruvannamalai",
  "Arani": "Thiruvannamalai",
  "Cheyyar": "Thiruvannamalai",
  "Chengam": "Thiruvannamalai",
  "Vandavasi": "Thiruvannamalai",
  "Keelpennathur": "Thiruvannamalai",
  "Tamarainagar": "Thiruvannamalai",
  "Namakkal": "Namakkal",
  "Tiruchengode": "Namakkal",
  "Rasipuram": "Namakkal",
  "Kumarapalayam": "Namakkal",
  "Paramathivelur": "Namakkal",
  "Mohanur": "Namakkal",
  "Sooramangalam": "Salem",
  "Ammapet": "Salem",
  "Athur": "Salem",
  "Thathakapatti": "Salem",
  "Mettur": "Salem",
  "Attayampatti": "Salem",
  "Hasthampatti": "Salem",
  "Elampillai": "Salem",
  "Thammampatti": "Salem",
  "Jalagandapuram": "Salem",
  "Edapadi": "Salem",
  "Mecheri": "Salem",
  "Vazhapadi": "Salem",
  "Sampath Nagar": "Erode",
  "Gobichettipalayam": "Erode",
  "Sathiyamagalam": "Erode",
  "Perundurai": "Erode",
  "R.S.Puram": "Coimbatore",
  "Singanallur": "Coimbatore",
  "Vadavalli": "Coimbatore",
  "Kuruchi": "Coimbatore",
  "Sulur": "Coimbatore",
  "Mettupalayam": "Coimbatore",
  "Pollachi": "Coimbatore",
  "Dharmapuri": "Dharmapuri",
  "Harur": "Dharmapuri",
  "Palacode": "Dharmapuri",
  "Pennagaram": "Dharmapuri",
  "Papparapatti": "Dharmapuri",
  "Krishnagiri": "Krishnagiri",
  "Hosur": "Krishnagiri",
  "Pochampalli": "Krishnagiri",
  "Uthangarai": "Krishnagiri",
  "Bargur": "Krishnagiri",
  "Theni": "Theni",
  "Periyakulam": "Theni",
  "Chinnamanur": "Theni",
  "Cumbum": "Theni",
  "Bodinayakkanur": "Theni",
  "Dindigul": "Dindigul",
  "Palani": "Dindigul",
  "Kodaikanal": "Dindigul",
  "Oddanchatram": "Dindigul",
  "Natham": "Dindigul",
  "Batlagundu": "Dindigul",
  "Anna Nagar": "Madurai",
  "Palanganatham": "Madurai",
  "BB Kulam": "Madurai",
  "Melur": "Madurai",
  "Thirumangalam": "Madurai",
  "Anaiyur": "Madurai",
  "Sivagangai": "Sivaganga",
  "Karaikudi": "Sivaganga",
  "Devakottai": "Sivaganga",
  "Singampunari": "Sivaganga",
  "Manamadurai": "Sivaganga",
  "Ramanathapuram": "Ramanathapuram",
  "Paramakudi": "Ramanathapuram",
  "Rameswaram": "Ramanathapuram",
  "Kamuthi": "Ramanathapuram",
  "Virudhunagar": "Virudhunagar",
  "Sivakasi": "Virudhunagar",
  "Rajapalayam": "Virudhunagar",
  "Srivilliputhur": "Virudhunagar",
  "Aruppukottai": "Virudhunagar",
  "Sattur": "Virudhunagar",
  "K.K.Nagar": "Tiruchirappalli",
  "Thennur": "Tiruchirappalli",
  "Gandhi Market": "Tiruchirappalli",
  "Thuraiyur": "Tiruchirappalli",
  "Manapparai": "Tiruchirappalli",
  "Lalgudi": "Tiruchirappalli",
  "Musiri": "Tiruchirappalli",
  "Perambalur": "Perambalur",
  "Karur": "Karur",
  "Kulithalai": "Karur",
  "Pudukottai": "Pudukkottai",
  "Aranthangi": "Pudukkottai",
  "Gandarvakottai": "Pudukkottai",
  "Viralimalai": "Pudukkottai",
  "Alangudi": "Pudukkottai",
  "Thanjavur": "Thanjavur",
  "Kumbakonam": "Thanjavur",
  "Pattukottai": "Thanjavur",
  "Orathanadu": "Thanjavur",
  "Tiruvarur": "Tiruvarur",
  "Mannargudi": "Tiruvarur",
  "Thiruthuraipoondi": "Tiruvarur",
  "Nagapattinam": "Nagapattinam",
  "Mayiladuthurai": "Mayiladuthurai",
  "Sirkali": "Mayiladuthurai",
  "Kandiyaperi": "Tirunelveli",
  "Melapalayam": "Tirunelveli",
  "Ambasamudram": "Tirunelveli",
  "NGO Colony": "Tirunelveli",
  "Tuticorin": "Thoothukudi",
  "Kovilpatti": "Thoothukudi",
  "Vadaseri": "Kanniyakumari",
  "Myladi": "Kanniyakumari",
  "Ariyalur": "Ariyalur",
  "Jeyankondam": "Ariyalur",
  "Udhagamandalam": "The Nilgiris",
  "Coonoor": "The Nilgiris",
  "Kothagiri": "The Nilgiris",
  "Gudalur": "The Nilgiris",
  "Palladam": "Tiruppur",
  "Udumalpet": "Tiruppur",
  "Tiruppur (North)": "Tiruppur",
  "Tiruppur (South)": "Tiruppur",
  "Dharapuram": "Tiruppur",
  "Kangayam": "Tiruppur",
  "Sankarankoil": "Tenkasi",
  "Tenkasi": "Tenkasi",
  "Pallavaram": "Chengalpattu",
  "Chengalpet": "Chengalpattu",
  "Medavakkam": "Chengalpattu",
  "Nanganallur": "Chengalpattu",
  "Madhuranthagam": "Chengalpattu",
  "Keelkattalai": "Chengalpattu",
  "Jameenrayapettai": "Chengalpattu",
  "Guduvancheri": "Chengalpattu",
  "Thirukalukundram": "Chengalpattu",
  "Ranipettai": "Ranipet",
  "Arcot": "Ranipet",
  "Vaniyampadi": "Tirupattur",
  "Tirupathur": "Tirupattur",
  "Natrampalli": "Tirupattur",
  "Kallakurichi": "Kallakurichi",
  "Ulundurpettai": "Kallakurichi",
  "Sankarapuram": "Kallakurichi"
};

export const MARKET_DISTRICT_MAP = districtMarketMap;

export const TN_DISTRICTS: string[] = [
  "Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore",
  "Dharmapuri", "Dindigul", "Erode", "Kallakurichi", "Kancheepuram",
  "Kanniyakumari", "Karur", "Krishnagiri", "Madurai", "Mayiladuthurai",
  "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai",
  "Ramanathapuram", "Ranipet", "Salem", "Sivaganga", "Tenkasi",
  "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli",
  "Tirupattur", "Tiruppur", "Tiruvallur", "Thiruvannamalai", "Tiruvarur",
  "Vellore", "Villupuram", "Virudhunagar"
];

export function getDistrictForMarket(marketName: string): string {
  if (!marketName) return "Tamil Nadu";
  const clean = marketName.trim();
  if (districtMarketMap[clean]) return districtMarketMap[clean];

  for (const [m, d] of Object.entries(districtMarketMap)) {
    if (clean.toLowerCase().includes(m.toLowerCase()) || m.toLowerCase().includes(clean.toLowerCase())) {
      return d;
    }
  }

  for (const d of TN_DISTRICTS) {
    if (clean.toLowerCase().includes(d.toLowerCase())) {
      return d;
    }
  }

  return "Tamil Nadu";
}
