import fs from "fs";

export const TN_OFFICIAL_CROPS = [
  { id: "8", name: "Tomato", category: "Vegetables", aliases: ["thakkali"] },
  { id: "9", name: "Potato", category: "Vegetables", aliases: ["urulaikizhangu", "aloo"] },
  { id: "10", name: "Small Onion", category: "Vegetables", aliases: ["shallot", "chinna vengayam", "sambar onion", "onion"] },
  { id: "11", name: "Big Onion", category: "Vegetables", aliases: ["periya vengayam", "bellary onion", "onion"] },
  { id: "12", name: "Chilli", category: "Vegetables", aliases: ["green chilli", "pachai milagai", "mirchi"] },
  { id: "13", name: "Brinjal", category: "Vegetables", aliases: ["eggplant", "kathirikai", "baingan"] },
  { id: "14", name: "Bhendi", category: "Vegetables", aliases: ["ladies finger", "okra", "vendaikkai", "bhindi"] },
  { id: "15", name: "Drumstick", category: "Vegetables", aliases: ["murungaikkai"] },
  { id: "16", name: "Ribbed gourd", category: "Vegetables", aliases: ["peerkangai", "ridge gourd", "turai"] },
  { id: "17", name: "Bottle Gourd", category: "Vegetables", aliases: ["sorakkay", "lauki"] },
  { id: "18", name: "Snake gourd", category: "Vegetables", aliases: ["pudalangai", "chichinda"] },
  { id: "19", name: "Bitter Gourd", category: "Vegetables", aliases: ["pavakkai", "karela"] },
  { id: "20", name: "Coconut", category: "Commercial", aliases: ["thengai", "nariyal", "copra"] },
  { id: "21", name: "Radish", category: "Vegetables", aliases: ["mullangi", "mooli"] },
  { id: "22", name: "Beans", category: "Vegetables", aliases: ["french beans"] },
  { id: "23", name: "Avarai", category: "Vegetables", aliases: ["broad beans", "field beans", "avaraikkai"] },
  { id: "24", name: "Carrot", category: "Vegetables", aliases: ["gajar"] },
  { id: "25", name: "Betel vine", category: "Commercial", aliases: ["vetrilai", "paan"] },
  { id: "26", name: "Mango (fruit)", category: "Fruits", aliases: ["mambazham", "aam"] },
  { id: "27", name: "Banana (fruit)", category: "Fruits", aliases: ["vazhaipazham", "kela"] },
  { id: "32", name: "Ginger", category: "Spices", aliases: ["inji", "adrak"] },
  { id: "34", name: "sapota", category: "Fruits", aliases: ["chiku", "chikoo", "sappotta"] },
  { id: "35", name: "Guava", category: "Fruits", aliases: ["koyyappazham", "amrood"] },
  { id: "36", name: "Custard Apple", category: "Fruits", aliases: ["seethappazham", "sitaphal"] },
  { id: "37", name: "Pappaya", category: "Fruits", aliases: ["pappali", "papita"] },
  { id: "38", name: "Cluster Beans", category: "Vegetables", aliases: ["kothavangai", "guar"] },
  { id: "39", name: "Ash gourd", category: "Vegetables", aliases: ["poosanaikkai", "petha"] },
  { id: "40", name: "Elephant foot Yam", category: "Vegetables", aliases: ["senai kizhangu", "suran", "jimikand"] },
  { id: "41", name: "Mango (veg)", category: "Vegetables", aliases: ["raw mango", "mangai", "kachha aam"] },
  { id: "42", name: "Tapioca", category: "Vegetables", aliases: ["maravalli kizhangu", "cassava", "kappa"] },
  { id: "43", name: "Baby Corn", category: "Cereals", aliases: ["corn", "maize"] },
  { id: "44", name: "Amla", category: "Fruits", aliases: ["nellikkai", "gooseberry", "indian gooseberry"] },
  { id: "45", name: "Banana (veg)", category: "Vegetables", aliases: ["vazhaikkai", "raw banana", "plantain"] },
  { id: "46", name: "Banana flower", category: "Vegetables", aliases: ["vazhaipoo"] },
  { id: "47", name: "Banana stem", category: "Vegetables", aliases: ["vazhaithandu"] },
  { id: "48", name: "Banana Leaf", category: "Commercial", aliases: ["vazhai ilai"] },
  { id: "49", name: "Greens", category: "Vegetables", aliases: ["keerai", "spinach", "palak"] },
  { id: "50", name: "Coriander Leaf", category: "Vegetables", aliases: ["kothamalli", "dhaniya patta"] },
  { id: "51", name: "Curry Leaf", category: "Vegetables", aliases: ["karuveppilai", "kadi patta"] },
  { id: "52", name: "Mint Leaf", category: "Vegetables", aliases: ["pudhina"] },
  { id: "53", name: "Pumpkin", category: "Vegetables", aliases: ["parangikkai", "kaddu"] },
  { id: "55", name: "Lemon", category: "Fruits", aliases: ["elumichai", "nimbu", "lime"] },
  { id: "56", name: "Beetroot", category: "Vegetables", aliases: ["beet"] },
  { id: "57", name: "Chow Chow", category: "Vegetables", aliases: ["chayote", "bangalore brinjal"] },
  { id: "58", name: "Cabbage", category: "Vegetables", aliases: ["muttaikose", "patta gobhi"] },
  { id: "59", name: "garlic", category: "Spices", aliases: ["poondu", "lahsun"] },
  { id: "60", name: "Cowpea", category: "Pulses", aliases: ["karamani", "thattai payaru", "black eyed pea", "lobia"] },
  { id: "61", name: "Mochai", category: "Pulses", aliases: ["hyacinth bean", "field bean"] },
  { id: "62", name: "Colacasia", category: "Vegetables", aliases: ["seppankizhangu", "arbi", "taro"] },
  { id: "63", name: "Sweet Potato", category: "Vegetables", aliases: ["sakkaravalli kizhangu", "shakarkand"] },
  { id: "64", name: "Kovvaikai", category: "Vegetables", aliases: ["ivy gourd", "tindora", "kundru"] },
  { id: "65", name: "Cucumber", category: "Vegetables", aliases: ["vellarikkai", "kheera"] },
  { id: "66", name: "Cauliflower", category: "Vegetables", aliases: ["gobi", "phool gobhi"] },
  { id: "67", name: "Groundnut", category: "Oilseeds", aliases: ["peanut", "verkadalai", "kadalai", "mungfali"] },
  { id: "68", name: "Sweet corn", category: "Cereals", aliases: ["corn", "maize", "cholam"] },
  { id: "69", name: "Mushroom", category: "Vegetables", aliases: ["kaalan", "khumb"] },
  { id: "70", name: "Knol Khol", category: "Vegetables", aliases: ["kohlrabi", "noolkol"] },
  { id: "71", name: "Turnip", category: "Vegetables", aliases: ["shalgam"] },
  { id: "72", name: "Peas", category: "Vegetables", aliases: ["pattani", "matar", "green peas"] },
  { id: "73", name: "Brocoli", category: "Vegetables", aliases: ["broccoli"] },
  { id: "74", name: "Capsicum", category: "Vegetables", aliases: ["kudai milagai", "shimla mirch", "bell pepper"] },
  { id: "75", name: "Pomegranate", category: "Fruits", aliases: ["madhulai", "anar"] },
  { id: "76", name: "Grapes", category: "Fruits", aliases: ["drakshai", "angoor"] },
  { id: "77", name: "Apple", category: "Fruits", aliases: ["seb"] },
  { id: "78", name: "Orange", category: "Fruits", aliases: ["kamala", "santra"] },
  { id: "79", name: "Sweet lime", category: "Fruits", aliases: ["sathukudi", "mosambi"] },
  { id: "80", name: "Pinapple", category: "Fruits", aliases: ["annasi", "ananas", "pineapple"] },
  { id: "81", name: "Muskmelon", category: "Fruits", aliases: ["keerani", "kharbuja"] },
  { id: "82", name: "Watermelon", category: "Fruits", aliases: ["tharpoosani", "tarbooz"] },
  { id: "83", name: "Jackfruit", category: "Fruits", aliases: ["pala pazham", "kathal"] },
  { id: "84", name: "Pear", category: "Fruits", aliases: ["berikkai", "nashpati"] },
  { id: "85", name: "Sundaikai", category: "Vegetables", aliases: ["turkey berry"] },
  { id: "86", name: "Fig", category: "Fruits", aliases: ["athi pazham", "anjeer"] },
  { id: "87", name: "Jamun", category: "Fruits", aliases: ["naga pazham", "black plum"] },
  { id: "88", name: "Goose berry (Nellikkai)", category: "Fruits", aliases: ["amla", "nellikkai"] },
  { id: "89", name: "Citron (Narthai)", category: "Fruits", aliases: ["narthangai"] },
  { id: "90", name: "Tamarind", category: "Spices", aliases: ["puli", "imli"] },
  { id: "91", name: "Perandai", category: "Vegetables", aliases: ["adamant creeper", "pirandai"] },
  { id: "92", name: "Butter Beans", category: "Pulses", aliases: ["lima beans"] },
  { id: "93", name: "Soya Beans", category: "Pulses", aliases: ["soybean", "soya"] },
  { id: "94", name: "Karunaikizhangu", category: "Vegetables", aliases: ["yam", "suran"] },
  { id: "95", name: "Dragon fruit", category: "Fruits", aliases: ["pitaya"] },
  { id: "96", name: "Siru Kizhagu", category: "Vegetables", aliases: ["chinese potato"] },
  { id: "97", name: "Bajji chilli", category: "Vegetables", aliases: ["chilli", "bhavnagri mirchi"] },
  { id: "98", name: "Onion leaf", category: "Vegetables", aliases: ["spring onion", "vengaya thal"] },
  { id: "99", name: "Water Apple", category: "Fruits", aliases: ["rose apple", "pani seb"] },
  { id: "100", name: "Red Chilli", category: "Spices", aliases: ["kanja milagai", "lal mirch", "chilli"] },
  { id: "101", name: "Wood Apple", category: "Fruits", aliases: ["vilampazham", "bel"] },
  { id: "102", name: "Double Beans", category: "Pulses", aliases: ["beans"] },
  { id: "103", name: "Bread Fruit", category: "Vegetables", aliases: ["eera pala"] },
  { id: "104", name: "Nerium", category: "Flowers", aliases: ["arali"] },
  { id: "105", name: "kakatan", category: "Flowers", aliases: ["kakada"] },
  { id: "106", name: "Rose", category: "Flowers", aliases: ["roja", "gulab"] },
  { id: "107", name: "Marigold", category: "Flowers", aliases: ["samandhi", "genda"] },
  { id: "108", name: "Tuberose", category: "Flowers", aliases: ["sambangi", "rajnigandha"] },
  { id: "109", name: "Jasmine", category: "Flowers", aliases: ["malli", "malligai", "mogra"] },
  { id: "110", name: "crossandra", category: "Flowers", aliases: ["kanakambaram"] },
  { id: "111", name: "Pichi", category: "Flowers", aliases: ["jathi malli"] },
  { id: "112", name: "Red Cabbage", category: "Vegetables", aliases: ["purple cabbage"] },
  { id: "113", name: "Redgram", category: "Pulses", aliases: ["thuvarai", "tur", "arhar", "pigeon pea", "pulses", "gram"] },
  { id: "114", name: "Marikozhunthu", category: "Flowers", aliases: ["maruvu", "davana"] },
  { id: "115", name: "Wild lemon", category: "Fruits", aliases: ["kattu elumichai"] },
  { id: "116", name: "Tender Coconut", category: "Commercial", aliases: ["elaneer", "daab", "coconut"] },
  { id: "117", name: "Sugarcane", category: "Commercial", aliases: ["karumbu", "ganna"] },
  { id: "118", name: "Tulasi", category: "Herbs", aliases: ["holy basil"] },
  { id: "119", name: "Ma.Inji", category: "Vegetables", aliases: ["mango ginger", "amada"] },
  { id: "121", name: "Purple Yam", category: "Vegetables", aliases: ["vethalai valli kizhangu"] },
  { id: "122", name: "Pidikarunai", category: "Vegetables", aliases: ["small yam"] },
  { id: "123", name: "Turmeric Bunch", category: "Spices", aliases: ["turmeric", "manjal", "haldi", "turmeric raw", "turmeric finger", "curcuma"] },
  { id: "124", name: "Panangkizhangu", category: "Vegetables", aliases: ["palmyra sprout"] },
  { id: "125", name: "Palmyra fruit", category: "Fruits", aliases: ["nongu", "tadgola"] },
  { id: "126", name: "Athalakkai", category: "Vegetables", aliases: ["wild bitter gourd"] },
  { id: "127", name: "Ixora", category: "Flowers", aliases: ["idli poo"] },
  { id: "128", name: "Kadampam", category: "Flowers", aliases: ["mixed flowers"] },
  { id: "129", name: "Tomato(Local)", category: "Vegetables", aliases: ["nattu thakkali", "tomato", "thakkali"] },
  { id: "130", name: "Tomato (Bangalore)", category: "Vegetables", aliases: ["apple thakkali", "hybrid tomato", "tomato"] },
  { id: "131", name: "Brinjal (Green Striped)", category: "Vegetables", aliases: ["brinjal", "kathirikai"] },
  { id: "132", name: "Brinjal (Blue Striped)", category: "Vegetables", aliases: ["brinjal", "kathirikai"] },
  { id: "133", name: "Brinjal (White)", category: "Vegetables", aliases: ["brinjal", "kathirikai", "vellai kathiri"] },
  { id: "134", name: "Brinjal (Spiny)", category: "Vegetables", aliases: ["mullu kathirikai", "brinjal", "kathirikai"] },
  { id: "135", name: "Bitter Gourd (Big)", category: "Vegetables", aliases: ["periya pavakkai", "bitter gourd", "pavakkai"] },
  { id: "136", name: "Bitter Gourd (Mithi Pagal)", category: "Vegetables", aliases: ["mithi pavakkai", "small bitter gourd", "bitter gourd"] },
  { id: "137", name: "Potato (Ooty)", category: "Vegetables", aliases: ["ooty urulaikizhangu", "potato"] },
  { id: "138", name: "Potato (Agra)", category: "Vegetables", aliases: ["agra potato", "potato"] },
  { id: "139", name: "Avarai (Big)", category: "Vegetables", aliases: ["periya avarai", "avarai", "broad beans"] },
  { id: "140", name: "Avarai (Nadu)", category: "Vegetables", aliases: ["nattu avarai", "avarai"] },
  { id: "141", name: "garlic (Nadu)", category: "Spices", aliases: ["nattu poondu", "garlic", "poondu"] },
  { id: "142", name: "garlic (Malai Poondu)", category: "Spices", aliases: ["kodaikanal malai poondu", "hill garlic", "garlic", "poondu"] },
  { id: "143", name: "Mango (Neelam)", category: "Fruits", aliases: ["neelam mangai", "mango"] },
  { id: "144", name: "Mango (Banganapalli)", category: "Fruits", aliases: ["banganapalli mango", "mango"] },
  { id: "145", name: "Mango (Alphonso)", category: "Fruits", aliases: ["alphonso mango", "gundu mango", "mango"] },
  { id: "146", name: "Mango (Bangalora)", category: "Fruits", aliases: ["totapuri mango", "kili mooku mangai", "mango"] },
  { id: "147", name: "Mango (Imam Pasand)", category: "Fruits", aliases: ["himayat mango", "imam pasand", "mango"] },
  { id: "148", name: "Mango (Malgova)", category: "Fruits", aliases: ["malgova mango", "mango"] },
  { id: "149", name: "Mango (Sindhura)", category: "Fruits", aliases: ["sindhoori mango", "mango"] },
  { id: "150", name: "Mango (Rumani)", category: "Fruits", aliases: ["rumani mango", "mango"] },
  { id: "151", name: "Banana (Red banana)", category: "Fruits", aliases: ["sevvaazhai", "red banana", "banana"] },
  { id: "152", name: "Banana (Nendran)", category: "Fruits", aliases: ["nendran banana", "banana chips vazhai", "banana"] },
  { id: "153", name: "Banana (Rasthali)", category: "Fruits", aliases: ["rasthali banana", "banana"] },
  { id: "154", name: "Banana  (Karpuravalli)", category: "Fruits", aliases: ["karpuravalli banana", "banana"] },
  { id: "155", name: "Banana (Poovan)", category: "Fruits", aliases: ["poovan banana", "banana"] },
  { id: "156", name: "Banana (Yelakki)", category: "Fruits", aliases: ["elakki banana", "ney vazhai", "banana"] },
  { id: "157", name: "Banana (Matti)", category: "Fruits", aliases: ["kanyakumari matti banana", "banana"] },
  { id: "158", name: "Banana (Nadu)", category: "Fruits", aliases: ["nattu vazhai", "banana"] },
  { id: "159", name: "Banana (Green banana)", category: "Fruits", aliases: ["pachai vazhai", "cavendish", "banana"] },
  { id: "161", name: "Plums", category: "Fruits", aliases: ["aloo bukhara"] },
  { id: "162", name: "Rambutan", category: "Fruits", aliases: ["rambutan"] }
];
